sudo: false
addons:
  apt:
    packages:
    - php5
bundler_args: ""
before_install:
  - npm install -g coffeelint
  - rvm default do gem install execjs
  - git config --global user.name "Pre Commit"
  - git config --global user.email "pre-commit+travis@example.com"
  - gem update bundler
cache:
 - bundler
 - npm
language: ruby
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1
  - ruby-2.2
  - ruby-2.3.0
  - jruby
matrix:
  fast_finish: true
