before_install:
  - sudo apt-get install -y nodejs php5
  - rvm default do gem install execjs
  - git config --global user.name "Pre Commit"
  - git config --global user.email "pre-commit+travis@example.com"
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
